geoportal/accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = "accounts"

urlpatterns = [ 
    path('register/', registerPage, name = 'register'),
    path('login/', loginPage, name = 'login'),   
    path('logout/', logoutUser, name = 'logout'),   
    path('user-cab/', user_cab, name = 'userpage'),
    path('user-cab/create-datastore/', CreateGetDataStore.as_view(), name='create-datastore'),
    path('user-cab/add_layer/', addLayer, name = 'add-layer'),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

geoportal/main/urls.py
from django.urls import path

from .views import main_page, landing, leaflet

app_name = "main"

urlpatterns = [
    path("", main_page, name = "main"),
    path("landing/", landing, name = "landing"),
    path("leaflet/", leaflet, name="leaflet"),
]

geoportal/accounts/models.py
from django.db import models


# Create your models here.

geoportal/main/models.py
from django.db import models

# Create your models here.

geoportal/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms   

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        

geoportal/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.conf import settings 
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

from .forms import CreateUserForm
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from requests.auth import HTTPBasicAuth
from geo.Geoserver import Geoserver

from .configs import *

import psycopg2
import os
import json
import requests


@csrf_exempt
def registerPage(request):
    
    geo = Geoserver('http://127.0.0.1:8080/geoserver', username='admin', password='geoserver')
    
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request, user + " Ваш аккаунт создан, пожалуйста пройдите авторизацию")
            
            geo.create_workspace(workspace=user)

            return redirect("accounts:login")
    

    context = {"form": form}
    return render(request, "accounts/registration.html", context)

@csrf_exempt
def loginPage(request):
    if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")

            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                print(user)
                return redirect("accounts:userpage")
            else:
                messages.info(request, "Ошибка при вводе логина или пароля")
    context = {}
    return render(request, "accounts/login.html", context)


def logoutUser(request):
    logout(request)
    return redirect("accounts:login")

@login_required(login_url="accounts:login")
def user_cab(request):
    return render(request, "accounts/user_cab.html")


def postgre_con_create_db(db_name):
        try:
            con = psycopg2.connect(database="gis_layers", user=USER, password=PASSWORD, host=HOST, port=PORT)
            print("Connected to the Postgre")
        except Exception:
            print("error while connecting to Postgre")

        con.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        cursor = con.cursor()
        sqlCreateDatabase = "CREATE DATABASE "+db_name+";"

        cursor.execute(sqlCreateDatabase)
        print("DataBase created")

        try:
            con = psycopg2.connect( database=db_name ,user=USER, password=PASSWORD, host=HOST, port=PORT)
            print(f"Connected to {db_name} DB")
        except Exception:
            print("Unable to connect to the database")
        con.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
        
        cursor = con.cursor()    
        ext = "postgis"
        ext_query = "CREATE EXTENSION "+ext+";"

        try:
            cursor.execute(ext_query)
            print("extension created")
        except:
            print("extension didnt creat")
        
        con.commit()
        cursor.close()
        con.close()

class CreateGetDataStore(View):
    def __init__(self):
        self.geo = GEO
        self.user_workspace = None
        self.datastores = None
        self.template = "accounts/add_DB.html"
        self.default_db = "gis_layers"
        self.error_template = 0


    @method_decorator(login_required)
    def post(self, request):
        if request.method == "POST":
            user = request.user
            db_name = request.POST.get("db_name")
            if user is not None:
                try:
                    postgre_con_create_db(db_name)


                    ws = user
                    r_url = "http://localhost:8080/geoserver/rest/workspaces/{}/datastores"
                    formatted_url = r_url.format(ws)
                    r_headers = {'Content-type': 'application/json',  # Определение типа данных
                            'Accept': 'text/plain',
                            'Content-Encoding': 'utf-8'}
                    datas = {
                        "dataStore": {
                            "name": f"{db_name}",
                            "connectionParameters": {
                                "entry": [
                                    {"@key":"host","$":HOST},
                                    {"@key":"port","$":PORT},
                                    {"@key":"database","$":f"{db_name}"},
                                    {"@key":"user","$":USER},
                                    {"@key":"passwd","$":PASSWORD},
                                    {"@key":"dbtype","$":"postgis"}
                                ]
                            }
                        }
                    }
                    r = requests.post(formatted_url, data = json.dumps(datas), auth =HTTPBasicAuth(GEOSERVER_LOG, GEOSERVER_PASS), headers = r_headers) 
                    if r.status_code == 201: 
                        print("A datastore has been сreated!")
                    else:
                        print("A datastore has already created")

                    return render(request, self.template)
                except Exception:
                    print("Не удалось создать базу в постгре или в геосервере")
                    return render(request, "accounts/error_page.html")
            else:
                return render(request, "accounts/error_page.html")


    @method_decorator(login_required)
    def get(self, request):
        if request.method == "GET":
            user = request.user
            if user is not None:
                try:
                    self.user_workspace = self.geo.get_workspace(workspace=user)
                    self.datastores = self.geo.get_datastores(workspace=user)

                    
                    data_iter = self.datastores["dataStores"]["dataStore"]
                    ds_list = []
                    for i in data_iter:
                        ds_list.append(i["name"])
                    print(ds_list)
                        
                    return  render(request, self.template, context={"ds_list": ds_list})

                except Exception:
                    print("Something goes wrong")
            
        return render(request, self.template)  



@csrf_exempt
@login_required(login_url="accounts:login")
def addLayer(request):
    
    file_system = None
    file_folder = None
    file_dir    = None
    datast      = ""
    
    geo = Geoserver('http://127.0.0.1:8080/geoserver', username='admin', password='geoserver')
    
    if request.method == "POST":
        logged_user = request.user
        if logged_user is not None:
            logged_user = str(logged_user)            
            uploaded_file = request.FILES["upload_file"]
            if not os.path.exists(os.path.join(settings.MEDIA_ROOT, logged_user)):
                try:
                    os.mkdir(os.path.join(settings.MEDIA_ROOT, logged_user))      
                except Exception:
                    print("Error while creating direction to the user")
            
            file_folder = os.path.join(settings.MEDIA_ROOT, logged_user)
            file_system = FileSystemStorage(file_folder)
            file_system.save(uploaded_file.name, uploaded_file)
            file_folder = str(file_folder)
            file_dir = os.path.join(file_folder, uploaded_file.name)
            
            datastores = geo.get_datastores(workspace=logged_user) 
            data_iter = datastores['dataStores']['dataStore']
            
            for i in data_iter:
                datast = i['name']
            
            try:
                geo.create_shp_datastore(path=file_dir, store_name=datast, workspace=logged_user)
                print("Shapefile added and published")

            except Exception:
                print("Error while adding shape")
            
            
        else:
            print(f"не удалось сохранить .zip")
    return render(request, "accounts/upload_shape.html")
    

geoportal/main/views.py
from django.shortcuts import render

# Create your views here.


def main_page(request):
    return render(request, "main/main.html")


def landing(request):
    return render(request, "main/landing.html")

def leaflet(request):
    return render(request, "main/leaflet.html")

geoportal/accounts/templates/accounts/add_DB.html
{% extends 'accounts/base_template.html' %}
{% load static %}

{% block title %}
    Add DB2
{% endblock %}


{% block logo %}
        <a href="{% url 'accounts:userpage' %}" class="brand-logo">{{ request.user }}</a>
{% endblock %}


{% block links %}
    <li><a href="{% url 'accounts:add-layer' %}">Создать хранилище</a></li>
    <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
{% endblock %}  


{% block content %}

    <h4 class="center-align blue-text text-darken-1">Создание хранилища</h4>
    <br>
    <div class="row">
        <form autocomplete="off" method="POST" class="col s6">
            <div class="row">
                <div class="input-field col s12 ">
                    {% csrf_token %}
                    <input id="db_name" name="db_name" type="text" class="validate blue-text text-darken-1">
                    <label class="blue-text text-darken-1" for="db_name">Название хранилища</label>

                    <button class="btn waves-effect waves-light blue darken-1" type="submit" name="action">Создать
                        <i class="material-icons right">data_usage</i>
                    </button>

                    <br>
                    <br>

                    
                </div>
            </div>
        </form>


        <div class="col s6">
            <table class="centered">
                <tbody>
                    {% for items in ds_list %}   
                    <tr>
                        <td>{{ items }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
                    
        </div>

    </div>
{% endblock %}

geoportal/accounts/templates/accounts/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oops</title>
    <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Semi+Condensed:100,200,300,400" rel="stylesheet">
    <style>
        /**/
:root {
  --main-color: #eaeaea;
  --stroke-color: black;
  
}
/**/
body {
  background: var(--main-color);
}
h1 {
  margin: 100px auto 0 auto;
  color: var(--stroke-color);
  font-family: 'Encode Sans Semi Condensed', Verdana, sans-serif;
  font-size: 10rem; line-height: 10rem;
  font-weight: 200;
  text-align: center;
}
h2 {
  margin: 20px auto 30px auto;
  font-family: 'Encode Sans Semi Condensed', Verdana, sans-serif;
  font-size: 1.5rem;
  font-weight: 200;
  text-align: center;
}
h1, h2 {
  -webkit-transition: opacity 0.5s linear, margin-top 0.5s linear; /* Safari */
  transition: opacity 0.5s linear, margin-top 0.5s linear;
}
.loading h1, .loading h2 {
  margin-top: 0px;
  opacity: 0;  
}
.gears {
  position: relative;
  margin: 0 auto;
  width: auto; height: 0;
}
.gear {
  position: relative;
  z-index: 0;
  width: 120px; height: 120px;
  margin: 0 auto;
  border-radius: 50%;
  background: var(--stroke-color);
}
.gear:before{
  position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;
  z-index: 2;
  content: "";
  border-radius: 50%;
  background: var(--main-color);
}
.gear:after {
  position: absolute; left: 25px; top: 25px;
  z-index: 3;
  content: "";
  width: 70px; height: 70px;
  border-radius: 50%;
  border: 5px solid var(--stroke-color);
  box-sizing: border-box;
  background: var(--main-color);
}
.gear.one {
  left: -130px;
}
.gear.two {
  top: -75px;
}
.gear.three {
  top: -235px;
  left: 130px;
}
.gear .bar {
  position: absolute; left: -15px; top: 50%;
  z-index: 0;
  width: 150px; height: 30px;
  margin-top: -15px;
  border-radius: 5px;
  background: var(--stroke-color);
}
.gear .bar:before {
  position: absolute; left: 5px; top: 5px; right: 5px; bottom: 5px;
  z-index: 1;
  content: "";
  border-radius: 2px;
  background: var(--main-color);
}
.gear .bar:nth-child(2) {
  transform: rotate(60deg);
  -webkit-transform: rotate(60deg);
}
.gear .bar:nth-child(3) {
  transform: rotate(120deg);
  -webkit-transform: rotate(120deg);
}
@-webkit-keyframes clockwise {
  0% { -webkit-transform: rotate(0deg);}
  100% { -webkit-transform: rotate(360deg);}
}
@-webkit-keyframes anticlockwise {
  0% { -webkit-transform: rotate(360deg);}
  100% { -webkit-transform: rotate(0deg);}
}
@-webkit-keyframes clockwiseError {
  0% { -webkit-transform: rotate(0deg);}
  20% { -webkit-transform: rotate(30deg);}
  40% { -webkit-transform: rotate(25deg);}
  60% { -webkit-transform: rotate(30deg);}
  100% { -webkit-transform: rotate(0deg);}
}
@-webkit-keyframes anticlockwiseErrorStop {
  0% { -webkit-transform: rotate(0deg);}
  20% { -webkit-transform: rotate(-30deg);}
  60% { -webkit-transform: rotate(-30deg);}
  100% { -webkit-transform: rotate(0deg);}
}
@-webkit-keyframes anticlockwiseError {
  0% { -webkit-transform: rotate(0deg);}
  20% { -webkit-transform: rotate(-30deg);}
  40% { -webkit-transform: rotate(-25deg);}
  60% { -webkit-transform: rotate(-30deg);}
  100% { -webkit-transform: rotate(0deg);}
}
.gear.one {
  -webkit-animation: anticlockwiseErrorStop 2s linear infinite;
}
.gear.two {
  -webkit-animation: anticlockwiseError 2s linear infinite;
}
.gear.three {
  -webkit-animation: clockwiseError 2s linear infinite;
}
.loading .gear.one, .loading .gear.three {
  -webkit-animation: clockwise 3s linear infinite;
}
.loading .gear.two {
  -webkit-animation: anticlockwise 3s linear infinite;
}
    </style>
</head>
<body class="loading">
    <h1>500</h1>
    <h2>Unexpected Error <b>:(</b></h2>
    <div class="gears">
      <div class="gear one">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
      </div>
      <div class="gear two">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
      </div>
      <div class="gear three">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script>
        $(function() {
            setTimeout(function(){
                $('body').removeClass('loading');
            }, 1000);
        });

    </script>
  </body>
</html>

geoportal/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
    <style>
        body {
            background: #222;
            background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://unsplash.it/1200/800/?random');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
          }
          .container {
            background: white;
            padding: 20px 25px;
            border: 5px solid #26a69a;
            width: 550px;
            height: auto;
            box-sizing: border-box;
            position: relative;
          }
          .col.s6 > .btn {
             width: 100%;
          }
          .gender-male,.gender-female {
            display: inline-block;
          }
          .gender-female {
            margin-left: 35px;
          }
          radio:required {
            border-color: red;
          }
          .container {
            animation: showUp 0.5s cubic-bezier(0.18, 1.3, 1, 1) forwards;
          }
          
          @keyframes showUp {
            0% {
              transform: scale(0);
            }
            100% {
              transoform: scale(1);
            }
          }
          .row {margin-bottom: 10px;}
          
          .ngl {
            position: absolute;
            top: -20px;
            right: -20px;
          }
          
    </style> 
</head>
<body>
    <div class="container">
        <div class="row">
            <form autocomplete="off" class="col s12" id="reg-form" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <input placeholder="Username" name="username" id="first_name" type="text" class="validate" required>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input placeholder="Password" name = "password" id="password" type="password" class="validate" minlength="6" required>
                    </div>
                </div>
                <div class="input-field col s6 offset-s3">
                    <button 
                        class="btn btn-large btn-register waves-effect waves-light " 
                        type="submit" 
                        name="action">
                            Login<i class="material-icons "></i>
                    </button>
                </div>
                <div class="col s12 offset-s2">
                  <p>У Вас нет аккаунта? <a href="{% url 'accounts:register' %}">Зарегистрируйтесь!</a></p>
                </div>
            </form>
            <br>
            <br>
            {% for message in messages %}
              <p id="messages">{{message}}</p>
            {% endfor %}
        </div>
    </div>
    
        
</body>
</html>
        

geoportal/accounts/templates/accounts/main.html
{% extends 'accounts/base_template.html' %}
{% load static %}

    {% block title %}
        Главная страница
    {% endblock %}

    {% block navbar %}
        
    {% endblock %}

    {% block content %}
        <h1>
            Content from Main
        </h1>
    {% endblock %}

    

geoportal/accounts/templates/accounts/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
    <title>Регистрация</title>
    <script>
        $(document).ready(function() {
            $('select').material_select();
          });
    </script>
    <style>
        body {
            background: #222;
            background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('https://unsplash.it/1200/800/?random');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            }
            .container {
            background: white;
            padding: 20px 25px;
            border: 5px solid #26a69a;
            width: 550px;
            height: auto;
            box-sizing: border-box;
            position: relative;
            }
            .col.s6 > .btn {
                width: 100%;
            }
            .gender-male,.gender-female {
            display: inline-block;
            }
            .gender-female {
            margin-left: 35px;
            }
            radio:required {
            border-color: red;
            }
            .container {
            animation: showUp 0.5s cubic-bezier(0.18, 1.3, 1, 1) forwards;
            }
            
            @keyframes showUp {
            0% {
                transform: scale(0);
            }
            100% {
                transoform: scale(1);
            }
            }
            .row {margin-bottom: 10px;}
            
            .ngl {
            position: absolute;
            top: -20px;
            right: -20px;
            }
          
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <form autocomplete="off" method="POST" class="col s12" id="reg-form">
                <div class="row">
                    <div class="input-field col s12">
                        {{form.username.label}}
                        {{form.username}}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{form.email.label}}
                        {{form.email}}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{form.password1.label}}
                        {{form.password1}}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                      {{form.password2.label}}
                      {{form.password2}}
                    </div>
                  </div>
                <div class="row">        
                    <div class="input-field col s6 offset-s3">
                        <button 
                            class="btn btn-large btn-register waves-effect waves-light " 
                            type="submit" 
                            name="action">
                                Register<i class="material-icons "></i>
                        </button>
                    </div>
                </div>
            </form>
            {{form.errors}}
        </div>
    </div>
        
</body>
</html>

geoportal/accounts/templates/accounts/upload_shape.html
{% extends 'accounts/base_template.html' %}
{% load static %}

{% block title %}
    User Cab
{% endblock %}

    {% block logo %}
        {{ request.user }}</a>
    {% endblock %}

    {% block links %}
        <li><a href="{% url 'accounts:create-datastore' %}">Создать хранилище</a></li>
        <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
    {% endblock %}   


{% block content %}

    <h4 class="center-align blue-text text-darken-1">Загрузка слоя</h4>
    <br>
    <div class="row">
        <form method="POST" action="#" enctype="multipart/form-data" class="col s6">
            <div class="file-field input-field">
              <div class="btn blue darken-1">
                <span>File</span>
                <input type="file" name="upload_file">
              </div>
              <div class="file-path-wrapper">
                <input id="fileinp" class="file-path validate" placeholder="Укажите архив .zip с файлами shp, shx, prj, dbf " type="text">
              </div>
              <button class="btn waves-effect waves-light blue darken-1" type="submit" name="action">Создать
                <i class="material-icons right">data_usage</i>
              </button>
            </div>
          </form>
        <div style="background-color:blue; height:500px" class="col s6">

        </div>
    </div>
{% endblock %}

geoportal/accounts/templates/accounts/user_cab.html
{% extends 'accounts/base_template.html' %}
{% load static %}

    {% block title %}
        User Cab
    {% endblock %}

    {% block logo %}
      {{ request.user }}
    {% endblock %}

    {% block email %}
      {{ request.email }}
    {% endblock %}

    {% block links %}
      <li><a href="{% url 'accounts:create-datastore' %}">Создать хранилище</a></li>
      <li><a href="{% url 'accounts:add-layer' %}">Загрузить слой</a></li>
      <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
    {% endblock %}    

    {% block content %}
    <ul class="collapsible">
        <li class="active">
          <div class="collapsible-header">First</div>
          <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
        </li>
        <li>
          <div class="collapsible-header">Second</div>
          <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
        </li>
        <li>
          <div class="collapsible-header">Third</div>
          <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
        </li>
      </ul>

      <br>
      <br>
      <br>

      <div id="map"></div>
    {% endblock %}

    